---
title: "R Notebook"
output: html_notebook
---
rm(list = ls())

library(readstata13)
library(ggplot2)
library(igraph)
library(ggraph)
library(readr)
library(tidyverse)
library(plyr)

f <- "E:/Data/Net/"

for(k in 1:242) {
  
                  if(k==184 || k==189) next
  
                  nodes <- read.dta13(file.path(f, paste0("Node_", k, ".dta")))
                  edges <- read.dta13(file.path(f, paste0("Edge_", k, ".dta")))
  
                  g1 <- graph_from_data_frame(d=edges, vertices = nodes, directed = F)
                  V(g1)$size <- strength(g1)
  
  
                  png(paste0(k, ".png"), 3000, 1500)
  
                  par(mar=c(0,0,0,0)); plot(g1,
                            vertex.color=vertex_attr(g1)$castecode,
                            vertex.label.color = "black", 
                            vertex.label.cex = .70, 
                            edge.curved=.25, 
                            edge.color="red") 
  
                  dev.off()
                  }
```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
